version: '3.3'

networks:
  net:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    networks:
      - net
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: kafka
    container_name: kafka
    restart: always

  cassandra:
    image: bitnami/cassandra:latest
    hostname: cassandra
    container_name: cassandra
    ports:
      - 9042:9042
    networks:
      - net
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
      - CASSANDRA_TRANSPORT_PORT_NUMBER=7000
      - CASSANDRA_HOST=cassandra
    volumes:
      - ./data/Data.cql:/schema.cql

  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2-java11
    container_name: spark-master
    hostname: spark-master
    healthcheck:
      interval: 5s
      retries: 100
    ports:
      - 8080:8080
      - 7077:7077
      - 4040:4040
      - 4041:4041
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - net
    volumes:
      - ./scripts/CreateStream.scala:/CreateStream.scala
      - ./spark-processor/target:/opt/spark-data

  spark-worker-1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2-java11
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - net
