#!/bin/sh

## Download relevant packages into interpreter and Start spark streaming from Kafka
docker exec spark-master /spark/bin/spark-shell --packages "com.datastax.spark:spark-cassandra-connector_2.12:3.1.0","org.apache.spark:spark-streaming-kafka-0-10_2.12:3.1.1" -i ./CreateStream.scala
